In [41]:
from sklearn.datasets import load_iris

In [43]:
from sklearn import tree

In [33]:
import numpy as np

In [2]:
iris = load_iris()

In [5]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [29]:
print(iris.data[0])

[ 5.1  3.5  1.4  0.2]


In [31]:
print(iris.target[0])

0


In [35]:
train_target=np.delete(iris.target,[0,50,100])

In [46]:
train_data=np.delete(iris.data,[0,50,100],axis=0)

In [37]:
test_target= iris.target[[0,50,100]]

In [38]:
test_data= iris.data[[0,50,100]]

In [44]:
clf=tree.DecisionTreeClassifier()

In [52]:
clf=clf.fit(train_data,train_target)

In [55]:
print(clf.predict(test_data))

[0 1 2]


In [39]:
print(test_target)

[0 1 2]
